src/Entity/Trick.php
<?php

namespace App\Entity;

use App\Repository\TrickRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=TrickRepository::class)
 * @ORM\Table(name="trick", indexes={@ORM\Index(columns={"name", "content"}, flags={"fulltext"})})
 * @UniqueEntity("name")
 */
class Trick
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups({"loadMore"})
     */
    private ?int $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"loadMore"})
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 2,
     *      max = 30,
     *      minMessage = "Le titre doit contenir au minimum {{ limit }} caractères",
     *      maxMessage = "Le titre ne doit pas dépasser les {{ limit }} caractères"
     * )
     * @Assert\Unique()
     */
    private ?string $name;

    /**
     * @ORM\Column(type="text")
     * @Groups({"loadMore"})
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 10,
     *      max = 500,
     *      minMessage = "La déscription doit contenir au minimum {{ limit }} caractères",
     *      maxMessage = "Le titre ne doit pas dépasser les {{ limit }} caractères"
     * )
     */
    private ?string $content;

    /**
     * @ORM\Column(type="datetime")
     * @Groups({"loadMore"})
     * @Assert\NotBlank
     */
    private  $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private  $updateAt;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="tricks")
     */
    private ?Category $category;

    /**
     * @ORM\OneToMany(targetEntity=Picture::class, mappedBy="trick", orphanRemoval=true, cascade={"persist", "remove"}, fetch="EAGER")
     * @Assert\Valid()
     * @var Collection<int, Picture>
     */
    private $pictures;

    /**
     * @ORM\OneToMany(targetEntity=Video::class, mappedBy="trick", orphanRemoval=true, cascade={"persist", "remove"})
     * @Assert\Valid()
     * @var Collection<int, Video>
     */
    private $videos;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, orphanRemoval=true, mappedBy="trick", cascade={"remove"})
     */
    private $comments;

    /**
     * @var string
     * @Groups({"loadMore"})
     */
    private string $slug;

    public function __construct()
    {
        $this->pictures = new ArrayCollection();
        $this->videos = new ArrayCollection();
        $this->createdAt = new \DateTime();
        $this->comments = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->updateAt;
    }

    public function setUpdateAt(\DateTimeInterface $updateAt): self
    {
        $this->updateAt = $updateAt;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setTrick($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getTrick() === $this) {
                $picture->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Video[]
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos[] = $video;
            $video->setTrick($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): self
    {
        if ($this->videos->removeElement($video)) {
            // set the owning side to null (unless already changed)
            if ($video->getTrick() === $this) {
                $video->setTrick(null);
            }
        }

        return $this;
    }



    public function getDefaultPicture(){
        $first =  $this->pictures->first();
        return $first ? $first->getFilename() : "assets/img/tricks/snowboard1.jpeg";
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setTrick($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getTrick() === $this) {
                $comment->setTrick(null);
            }
        }

        return $this;
    }

    public function setSlug($slugger)
    {
        $this->slug = $slugger;
    }

    public function getSlug(): string
    {
        return $this->slug;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\TrickRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="app_home")
     */
    public function index(TrickRepository $trickRepository): Response
    {
        $tricks = $trickRepository->findBy([], [], 6, 0);
        return $this->render('home/home.html.twig', [
            'tricks' => $tricks
        ]);
    }
}

templates/home/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home
{% endblock %}
    {% block javascripts %}
        <script src="{{ asset('assets/js/apiTrick.js') }}"></script>
        <script src="{{ asset('assets/js/modal.js') }}" defer></script>
    {% endblock %}
{% block body %}
    <!-- START CONTENT -->
    <section>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm">
                    <h2 class="post-sub-title mx-4 my-5"><strong>Toutes les figures</strong></h2>
                </div>

            </div>
            <div class="row text-center trickListDefault">
                    {% for trick in tricks %}
                        <div class="col-sm-12 col-md-6 col-lg-4">
                            <div class="img-trick">
                                <a href="/trick/show/{{ trick.id }}/{{ trick.slug }}" class="">
                                    <img src="{{ trick.defaultPicture }}">
                                </a>
                            </div>
                            <div class="flex-column text-start mx-4">
                                <h2 class="post-title px-1">{{ trick.name }}
                                    {% if is_granted('ROLE_USER') %}
                                    <a href="{{ path('app_trick_edit', {'id': trick.id}) }}"><i class="bi bi-pen"
                                                                                                style="color: black;"></i></a>
                                        <span><button class="btn btn-danger btn-sm" id="button-remove-trick" data-link="/trick/delete/{{ trick.id }}"><i class="bi bi-trash"></i></button></span>
                                    {% endif %}
                                </h2>
                                <span class="meta-item px-1">
                            <i class="bi bi-tags-fill"></i>
                            Catégorie
                                <span class="post-category">{{ trick.category.name }}</span>
                            </span>
                                <br>
                                <span class="meta-item px-1">
                            <i class="bi bi-chat-right-text-fill"></i>
                            Commentaire
                                <span class="post-comment">{{ trick.comments.count }}</span>
                            </span>
                                <p class="post-content px-1">{{ trick.content }}</p>
                                <p class="px-1"><a href="/trick/show/{{ trick.id }}/{{ trick.slug }}" class="btn btn-primary">Lire
                                        plus</a></p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
        </div>
    </section>
    <template id="trickList">
                <div class="col-sm-12 col-md-6 col-lg-4 ">
                    <div class="img-trick">
                        <a href="#" class="">
                            <img src="">
                        </a>
                    </div>
                    <div class="flex-column text-start mx-4">
                        <h2 class="post-title px-1">
                            <a href=""><i class="bi bi-pen" style="color: black;"></i></a>
                            <button class="btn btn-danger btn-sm" id="button-remove-trick-js" data-link=""><i class="bi bi-trash"></i></button>
                        </h2>
                        <span class="meta-item px-1">
                            <i class="bi bi-tags-fill"></i>
                            Catégorie
                                <span class="post-category"></span>
                            </span>
                        <br>
                        <span class="meta-item px-1">
                            <i class="bi bi-chat-right-text-fill"></i>
                            Commentaire
                                <span class="post-comment"></span>
                            </span>
                        <p class="post-content px-1"></p>
                        <p class="px-1"><a href="" class="btn btn-primary">Lire
                                plus</a></p>
                    </div>
                </div>
    </template>

    <div class="row">
        <p class="text-center">
            <a class="btn btn-primary mt30 ajaxButton" href="">Charger plus</a>
            <img id="loadMoreGif" src="{{ asset('assets/img/loading.GIF') }}" alt="loading"
                 style="display: none;">
        </p>
    </div>
{% endblock %}